language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install: "pip install -r requirements.txt"
script: python ./DelogX/tests/test.py && python ./setup.py sdist
notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
